### ISSUE TITLE
Error:  undefined:bufio.NewScanner    and   undefined reference to 'kOpenSSLFunctionXXXX'

### ISSUE THREAD

**Issue by pengkunlunHIT** [devsisters/libquic#10]
There were two kinds of errors when i build libquic by Ninja  and make

1)When i  input Ninja in the shell,it begins building,but it ends with an error as follow:
![undefined bufio newscanner](https://cloud.githubusercontent.com/assets/9984580/8202356/c1c65318-150b-11e5-9164-4efc658085e1.png)

i go to see the code ,it it as follow:
![code](https://cloud.githubusercontent.com/assets/9984580/8202402/285d3e3e-150c-11e5-8382-c6d7244ac6c3.png)

2)When i input make -j 1 in the shell,the error is as follow:
![make](https://cloud.githubusercontent.com/assets/9984580/8202416/4db2c028-150c-11e5-82f3-d2c76fdbac9d.png)

Looking forward to your help sincerely, thanks very much!  :)

**Comment by serialx** [comment]
I think you should use a latest version of Go. Ubuntu's latest Go is 1.2, I think installing 1.4 might help the problem.

1. Uninstall golang `sudo apt-get purge golang`
2. Install latest version from https://golang.org/doc/install

**Comment by pengkunlunHIT** [comment]
thanks very much,this way did solve the problem.
It seems that the version of a software is indeed a problem which may cause confusion. :)
