### ISSUE TITLE
‘INT64_C’ was not declared in this scope

### ISSUE THREAD

**Issue by brickz** [devsisters/libquic#19]
Hi,all:
  When i run make as specified in the readme.md, some error occurred. The error is mainly due to the lack of declaration of INT64_C and UINT64_C.
 I find the reported missing declaration existed in the included file stdint.h. Can anyone tell me why the error occurred and how to fix it?
 My Os is Ubuntu 12.04.3 LTS。

**Comment by hodduc** [comment]
IMO This should be fixed by #24 -- by adding __STDC_CONSTANT_MACROS build flag.
Please feel free to reopen if it does not work yet.
