### ISSUE TITLE
OSS Hygiene: AUTHORS file should include Google et al.

### ISSUE THREAD

**Issue by jbenet** [devsisters/libquic#2]
Hey Guys,

Fantastic work. :heart: Cant wait to use libquic (and goquic) in [IPFS](http://ipfs.io).

This is a bit silly, but one of those important-to-do-eventually things. Your `AUTHORS` file only lists you guys. It would be good to either include all the authors of QUIC itself in it-- or include chromium's `AUTHORS` file inside `src/` (along with the other `LICENSE`), and reference it from your `AUTHORS` file.

again, thank you so much for making this.

**Comment by serialx** [comment]
Fixed in 209379bb906413979743850c8606c1fb60c3de47

Thanks for your feedback! :)
