### ISSUE TITLE
requiring go?

### ISSUE THREAD

**Issue by bagder** [devsisters/libquic#3]
Hi,

I would like to try out libquic for some experiments but I have no interest in using go, can we make the build process not require it?

**Comment by bagder** [comment]
Blah so the build process needs it. Grrr...

**Comment by No9** [comment]
Yeah +1 
But as I see it this is due to boringSSL. 
There was a suggestion to replace boringSSL with openSSL but I believe this is non-trivial :(
Maybe talk to boringSSL about that or look to patch that build process?

**Comment by bagder** [comment]
Yeah, but I already built boringssl standalone separately (unrelated to this) and that didn't need go... I'll see if I can make a patch or something for this.

**Comment by No9** [comment]
Cool because I only got as far as this go dep in boringSSL 
https://github.com/devsisters/libquic/blob/master/boringssl/CMakeLists.txt#L7 

Have you shared your goless boringSSL anywhere? 

I also dont see a go dep in here 
https://github.com/devsisters/libquic/blob/master/CMakeLists.txt 

Am I missing something?

**Comment by bagder** [comment]
I build boringssl stand-alone without go from https://boringssl.googlesource.com/boringssl

The go check is at https://github.com/devsisters/libquic/blob/master/boringssl/CMakeLists.txt#L7 and if removed, it causes a build failure later when the crypto/err/*.go stuff are handled.

**Comment by No9** [comment]
K so if we remove this https://github.com/devsisters/libquic/blob/master/CMakeLists.txt#L327 and put in the standalone boring are we closer to getting this?

**Comment by bagder** [comment]
yes we should be

**Comment by No9** [comment]
:) This makes me happy

**Comment by serialx** [comment]
Yes, we intend to keep dependencies minimal, but the boringssl build requires Go.

BTW, how did you build a stand-alone boringssl without Go?

**Comment by bagder** [comment]
@serialx git clone, cmake, build! There is no go dependency in the build files in that repo, and that's why I was so surprised that libquic has one.

**Comment by serialx** [comment]
@bagder Interesting, since boringssl master also has Go dependency:

https://boringssl.googlesource.com/boringssl/+/master/CMakeLists.txt#7

I will look into this issue and try to remove Go requirement if we can. :)

Thanks!
