### ISSUE TITLE
how to enable all the debug, for example : LOG DLOG VLOG PLOG DPLOG

### ISSUE THREAD

**Issue by y123456yz** [devsisters/libquic#38]
@serialx

I want to enable all the debug, what I should do?

thanks.

**Comment by y123456yz** [comment]
how to enable NDEBUG when I compile the code?

**Comment by y123456yz** [comment]
set(CMAKE_C_FLAGS_RELEASE "-DNDEBUG")  can resolve my question, thanks

**Comment by y123456yz** [comment]
please close the issue, thanks again.

**Comment by y123456yz** [comment]
@serialx 
how to enable NDEBUG when I compile the code?

can you help me.
thanks

**Comment by serialx** [comment]
I do not know the specifics about Chromium logging infrastructure. Please consult Chromium documents and mailing list.
