### ISSUE TITLE
Could you please tell me which version of chromium code used in this lib?

### ISSUE THREAD

**Issue by chqiwang** [devsisters/libquic#6]
I want to try the toy client&server but the version seems mismatch.

**Comment by serialx** [comment]
Chromium revision is located in: `https://github.com/devsisters/libquic/blob/master/DEPS#L6`

You can checkout revision `b55be9ede35c10a2623c3c348768db92069d7f10` in chromium git repository and to `gclient sync` to retrieve the dependency.

We plan to update our code to the latest chromium source code this week. Thanks!

**Comment by chqiwang** [comment]
Thank you!
