### ISSUE TITLE
error:Could not find Go

### ISSUE THREAD

**Issue by pengkunlunHIT** [devsisters/libquic#8]
When I input cmake  -GNinja in the shell, it shows an error as follows:
![2015-06-16 22 10 06](https://cloud.githubusercontent.com/assets/9984580/8187616/5175853a-1483-11e5-8695-d1c6d363c36b.png)

![2015-06-16 23 57 28](https://cloud.githubusercontent.com/assets/9984580/8187634/78995240-1483-11e5-98d9-f077b53bd859.png)

I am not skillful and strong, what should i do to solve this problem?
Looking forward to your help sincerely,  thanks very much!

**Comment by badara0z** [comment]
try
sudo apt-get install golang

**Comment by pengkunlunHIT** [comment]
thank you very much, it works!

**Comment by jllongbell** [comment]
centos系统如何解决？
